name: "Workflow for Go applications"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-build-test-lint:
    name: "Runs Go related CI steps"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
          cache: true

      - name: Build
        run: make build

      - name: Test
        run: make test
      
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest