name: "Workflow for Terraform configuration"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    uses: martelskiy/infrastructure/.github/workflows/terraform.yml@main
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      working-directory: ./deployments