name: "Workflow for Main branch"

on:
  push:
    branches: 
      - main

jobs:
  docker-build-push:
    uses: martelskiy/workflows/.github/workflows/docker.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      ecr-repository: ecs-healthcheck
      image-tag: 1.0.0
  