name: "Workflow for Main branch"

on:
  push:
    branches: 
      - main

jobs:
  terraform-deploy:
    uses: martelskiy/workflows/.github/workflows/terraform-deploy.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      working-directory: ./deployments
      environment: 'production'
  docker-build-push:
    uses: martelskiy/workflows/.github/workflows/docker.yml@main
    needs: [terraform-deploy]
    permissions:
      id-token: write
      contents: read
    with:
      ecr-repository: ecs-healthcheck
      image-tag: 1.0.0
  